set(C7222_GETTING_STARTED_DIR ${CMAKE_CURRENT_LIST_DIR})

if(NOT DEFINED C7222_GETTING_STARTED_BUILD)
    set(C7222_GETTING_STARTED_BUILD OFF)
endif()

message(STATUS "C7222_GETTING_STARTED_BUILD is defined: ${C7222_GETTING_STARTED_BUILD}")

if(C7222_GETTING_STARTED_BUILD)
    set(C7222_GETTING_STARTED "")

    add_library(C7222_GETTING_STARTED_FREERTOS_C INTERFACE)
    set_property(TARGET C7222_GETTING_STARTED_FREERTOS_C PROPERTY TARGET_NAME "getting-started-freertos-c")
    set_property(TARGET C7222_GETTING_STARTED_FREERTOS_C PROPERTY TARGET_PATH "${C7222_GETTING_STARTED_DIR}/freertos-c")
    target_sources(C7222_GETTING_STARTED_FREERTOS_C INTERFACE
        ${C7222_GETTING_STARTED_DIR}/freertos-c/main_freertos.c
    )
    target_include_directories(C7222_GETTING_STARTED_FREERTOS_C INTERFACE
        ${C7222_GETTING_STARTED_DIR}/freertos-c
    )
    list(APPEND C7222_GETTING_STARTED C7222_GETTING_STARTED_FREERTOS_C)

    add_library(C7222_GETTING_STARTED_FREERTOS_CPP INTERFACE)
    set_property(TARGET C7222_GETTING_STARTED_FREERTOS_CPP PROPERTY TARGET_NAME "getting-started-freertos-cpp")
    set_property(TARGET C7222_GETTING_STARTED_FREERTOS_CPP PROPERTY TARGET_PATH "${C7222_GETTING_STARTED_DIR}/freertos-cpp")
    target_sources(C7222_GETTING_STARTED_FREERTOS_CPP INTERFACE
        ${C7222_GETTING_STARTED_DIR}/freertos-cpp/main_freertos.cpp
    )
    target_include_directories(C7222_GETTING_STARTED_FREERTOS_CPP INTERFACE
        ${C7222_GETTING_STARTED_DIR}/freertos-cpp
    )
    list(APPEND C7222_GETTING_STARTED C7222_GETTING_STARTED_FREERTOS_CPP)

    list(LENGTH C7222_GETTING_STARTED _c7222_getting_started_count)
    if(_c7222_getting_started_count EQUAL 0)
        message(FATAL_ERROR "C7222_GETTING_STARTED_BUILD is ON but no getting-started targets were added.")
    endif()
endif()
