set(ELEC_C7222_BLE_EXAMPLES_DIR ${CMAKE_CURRENT_LIST_DIR})

if(C7222_PLATFORM STREQUAL "rpi_pico2w")
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/gap/ble-gap-example.cmake)
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/gatt-server/ble-gatt-server-example.cmake)
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/security-manager/ble-security-manager-example.cmake)
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/custom-service-rw/ble-custom-service-rw-example.cmake)
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/custom-service-notify/ble-custom-service-notify-example.cmake)
elseif(C7222_PLATFORM STREQUAL "rp2350_custom_board")
    include(${ELEC_C7222_BLE_EXAMPLES_DIR}/rp2350-custom-board-gatt-server/ble-rp2350-custom-board-gatt-server-example.cmake)
endif()
