set(ELEC_C7222_BLE_GAP_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_BLE_GAP_SOURCES
    "${ELEC_C7222_BLE_GAP_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.cpp")
file(GLOB ELEC_C7222_BLE_GAP_SOURCES_COMMON "${ELEC_C7222_BLE_GAP_DIR}/src/*.cpp")

add_library(ELEC_C7222_BLE_GAP INTERFACE)
target_sources(ELEC_C7222_BLE_GAP INTERFACE 
                    ${ELEC_C7222_BLE_GAP_SOURCES} 
                    ${ELEC_C7222_BLE_GAP_SOURCES_COMMON})

target_include_directories(ELEC_C7222_BLE_GAP INTERFACE "${ELEC_C7222_BLE_GAP_DIR}/include")
