if(NOT DEFINED C7222_EXAMPLE_BLE_GAP)
    set(C7222_EXAMPLE_BLE_GAP OFF)
endif()
if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

message(STATUS "C7222_EXAMPLE_BLE_GAP is defined: ${C7222_EXAMPLE_BLE_GAP}")

if(C7222_EXAMPLE_BLE_GAP)
    if(NOT C7222_ENABLE_BLE)
        message(FATAL_ERROR "C7222_EXAMPLE_BLE_GAP requires C7222_ENABLE_BLE=ON")
    endif()
    add_library(C7222_EXAMPLE_BLE_GAP INTERFACE)

    file(GLOB C7222_EXAMPLE_BLE_GAP_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/*.c
        ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    )

    target_sources(C7222_EXAMPLE_BLE_GAP INTERFACE
        ${C7222_EXAMPLE_BLE_GAP_SOURCES}
    )

    target_include_directories(C7222_EXAMPLE_BLE_GAP INTERFACE
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/../common
    )

    list(APPEND C7222_ENABLED_EXAMPLES C7222_EXAMPLE_BLE_GAP)
endif()
