if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

if(NOT C7222_ENABLE_BLE)
    message(STATUS "C7222_EXAMPLES_BUILD requires C7222_ENABLE_BLE=ON for BLE examples. Skipping BLE RP2350 custom board GATT server example...")
    return()
endif()

if(NOT "${C7222_PLATFORM}" STREQUAL "rp2350_custom_board")
    message(STATUS "Skipping BLE RP2350 custom board GATT server example (requires C7222_PLATFORM=rp2350_custom_board)")
    return()
endif()

add_library(C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER INTERFACE)
set_property(TARGET C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER PROPERTY TARGET_NAME "example-ble-rp2350-custom-board-gatt-server")
set_property(TARGET C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/board/*.c
    ${CMAKE_CURRENT_LIST_DIR}/board/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.cpp
)

if(DEFINED PICO_BTSTACK_PATH)
    list(APPEND C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER_SOURCES
        ${PICO_BTSTACK_PATH}/src/hci_transport_h4.c
        ${PICO_BTSTACK_PATH}/platform/embedded/btstack_uart_block_embedded.c
    )
endif()

target_sources(C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER INTERFACE
    ${C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER_SOURCES}
)

target_include_directories(C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/board
    ${CMAKE_CURRENT_LIST_DIR}/../common
)

target_link_libraries(C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER INTERFACE
    hardware_dma
    hardware_uart
)

target_compile_definitions(C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER INTERFACE
    HAVE_UART_DMA_SET_FLOWCONTROL=1
)

# Append the gatt files 
file(GLOB APP_GATT_FILES "${CMAKE_CURRENT_LIST_DIR}/*.gatt")
set_property(TARGET C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER APPEND PROPERTY GATT_FILES ${APP_GATT_FILES})
# append to the global list for examples to use
list(APPEND C7222_EXAMPLES C7222_EXAMPLE_BLE_RP2350_CUSTOM_BOARD_GATT_SERVER)
