set(ELEC_C7222_FREERTOS_WRAPPERS_DIR ${CMAKE_CURRENT_LIST_DIR})

if(DEFINED PICO_SDK_PATH AND NOT PICO_SDK_PATH STREQUAL "")
    file(GLOB ELEC_C7222_FREERTOS_WRAPPERS_PLATFORM_SOURCES
        "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/rpi_pico/*.cpp"
        "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/rpi_pico/*.c")
else()
    file(GLOB ELEC_C7222_FREERTOS_WRAPPERS_PLATFORM_SOURCES
        "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/grader/*.cpp"
        "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/grader/*.c")
endif()

file(GLOB ELEC_C7222_FREERTOS_WRAPPERS_COMMON_SOURCES
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/src/*.cpp"
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/src/*.c")

add_library(ELEC_C7222_FREERTOS_WRAPPERS INTERFACE)

target_sources(ELEC_C7222_FREERTOS_WRAPPERS
    INTERFACE
    ${ELEC_C7222_FREERTOS_WRAPPERS_COMMON_SOURCES}
    ${ELEC_C7222_FREERTOS_WRAPPERS_PLATFORM_SOURCES})

target_include_directories(ELEC_C7222_FREERTOS_WRAPPERS
    INTERFACE
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/include"
    "${ELEC_C7222_DIR}/utils/include")
