set(ELEC_C7222_FREERTOS_WRAPPERS_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_FREERTOS_WRAPPERS_PLATFORM_SOURCES
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.cpp"
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.c")

file(GLOB ELEC_C7222_FREERTOS_WRAPPERS_COMMON_SOURCES
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/src/*.cpp"
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/src/*.c")

add_library(ELEC_C7222_FREERTOS_WRAPPERS INTERFACE)

target_sources(ELEC_C7222_FREERTOS_WRAPPERS
    INTERFACE
    ${ELEC_C7222_FREERTOS_WRAPPERS_COMMON_SOURCES}
    ${ELEC_C7222_FREERTOS_WRAPPERS_PLATFORM_SOURCES})

target_include_directories(ELEC_C7222_FREERTOS_WRAPPERS
    INTERFACE
    "${ELEC_C7222_FREERTOS_WRAPPERS_DIR}/include"
    "${ELEC_C7222_DIR}/utils/include")
