set(ELEC_C7222_DEVICES_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_DEVICES_PLATFORM_SOURCES
    "${ELEC_C7222_DEVICES_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.cpp"
    "${ELEC_C7222_DEVICES_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.c")

file(GLOB ELEC_C7222_DEVICES_COMMON_SOURCES
    "${ELEC_C7222_DEVICES_DIR}/src/*.cpp"
    "${ELEC_C7222_DEVICES_DIR}/src/*.c")

if(NOT C7222_HAS_PICO_W_BOARD)
    list(FILTER ELEC_C7222_DEVICES_COMMON_SOURCES EXCLUDE REGEX ".*/c7222_pico_w_board\\.cpp$")
    list(FILTER ELEC_C7222_DEVICES_PLATFORM_SOURCES EXCLUDE REGEX ".*/c7222_pico_w_board\\.c$")
endif()

if(C7222_PLATFORM_USES_PICO_SDK AND NOT C7222_HAS_ONBOARD_LED)
    list(FILTER ELEC_C7222_DEVICES_COMMON_SOURCES EXCLUDE REGEX ".*/onboard_led\\.cpp$")
    list(FILTER ELEC_C7222_DEVICES_PLATFORM_SOURCES EXCLUDE REGEX ".*/onboard_led\\.cpp$")
endif()

add_library(ELEC_C7222_DEVICES INTERFACE)
target_sources(ELEC_C7222_DEVICES INTERFACE ${ELEC_C7222_DEVICES_COMMON_SOURCES})
target_sources(ELEC_C7222_DEVICES INTERFACE ${ELEC_C7222_DEVICES_PLATFORM_SOURCES})
target_include_directories(ELEC_C7222_DEVICES INTERFACE "${ELEC_C7222_DEVICES_DIR}/include")

target_compile_definitions(ELEC_C7222_DEVICES INTERFACE
    $<$<BOOL:${C7222_HAS_PICO_W_BOARD}>:C7222_HAS_PICO_W_BOARD=1>
    $<$<BOOL:${C7222_HAS_ONBOARD_LED}>:C7222_HAS_ONBOARD_LED=1>
)
