set(ELEC_C7222_DEVICES_DIR ${CMAKE_CURRENT_LIST_DIR})

if (DEFINED PICO_SDK_PATH AND NOT PICO_SDK_PATH STREQUAL "")
    file(GLOB ELEC_C7222_DEVICES_PLATFORM_SOURCES "${ELEC_C7222_DEVICES_DIR}/platform/rpi_pico/*.cpp")
else()
    file(GLOB ELEC_C7222_DEVICES_PLATFORM_SOURCES "${ELEC_C7222_DEVICES_DIR}/platform/grader/*.cpp")
endif()
file(GLOB ELEC_C7222_DEVICES_COMMON_SOURCES "${ELEC_C7222_DEVICES_DIR}/src/*.cpp")

add_library(ELEC_C7222_DEVICES INTERFACE)
target_sources(ELEC_C7222_DEVICES INTERFACE ${ELEC_C7222_DEVICES_COMMON_SOURCES})
target_sources(ELEC_C7222_DEVICES INTERFACE ${ELEC_C7222_DEVICES_PLATFORM_SOURCES})
target_include_directories(ELEC_C7222_DEVICES INTERFACE "${ELEC_C7222_DEVICES_DIR}/include")