if(NOT DEFINED C7222_EXAMPLE_FREERTOS_BOARD)
    set(C7222_EXAMPLE_FREERTOS_BOARD OFF)
endif()

message(STATUS "C7222_EXAMPLE_FREERTOS_BOARD is defined: ${C7222_EXAMPLE_FREERTOS_BOARD}")

if(C7222_EXAMPLE_FREERTOS_BOARD)
    add_library(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE)

    file(GLOB C7222_EXAMPLE_FREERTOS_BOARD_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/*.c
        ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    )

    target_sources(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE
        ${C7222_EXAMPLE_FREERTOS_BOARD_SOURCES}
    )

    target_include_directories(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE
        ${CMAKE_CURRENT_LIST_DIR}
    )

    list(APPEND C7222_ENABLED_EXAMPLES C7222_EXAMPLE_FREERTOS_BOARD)
endif()
