add_library(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE)
set_property(TARGET C7222_EXAMPLE_FREERTOS_BOARD PROPERTY TARGET_NAME "example-freertos-board")
set_property(TARGET C7222_EXAMPLE_FREERTOS_BOARD PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_FREERTOS_BOARD_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
)

target_sources(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE
    ${C7222_EXAMPLE_FREERTOS_BOARD_SOURCES}
)

target_include_directories(C7222_EXAMPLE_FREERTOS_BOARD INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
)

list(APPEND C7222_EXAMPLES C7222_EXAMPLE_FREERTOS_BOARD)
