if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

if(NOT C7222_ENABLE_BLE)
    message(STATUS "C7222_EXAMPLES_BUILD requires C7222_ENABLE_BLE=ON for BLE examples. Skipping BLE SECURITY MANAGER example...")
    return()
endif()

add_library(C7222_EXAMPLE_BLE_SECURITY_MANAGER INTERFACE)
set_property(TARGET C7222_EXAMPLE_BLE_SECURITY_MANAGER PROPERTY TARGET_NAME "example-ble-security-manager")
set_property(TARGET C7222_EXAMPLE_BLE_SECURITY_MANAGER PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_BLE_SECURITY_MANAGER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.cpp
)

target_sources(C7222_EXAMPLE_BLE_SECURITY_MANAGER INTERFACE
    ${C7222_EXAMPLE_BLE_SECURITY_MANAGER_SOURCES}
)

target_include_directories(C7222_EXAMPLE_BLE_SECURITY_MANAGER INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/../common
)

# Append the gatt files
file(GLOB APP_GATT_FILES "${CMAKE_CURRENT_LIST_DIR}/*.gatt")
set_property(TARGET C7222_EXAMPLE_BLE_SECURITY_MANAGER APPEND PROPERTY GATT_FILES ${APP_GATT_FILES})

# append to the global list for examples to use
list(APPEND C7222_EXAMPLES C7222_EXAMPLE_BLE_SECURITY_MANAGER)
