set(ELEC_C7222_BLE_GATT_DIR ${CMAKE_CURRENT_LIST_DIR})

if (DEFINED PICO_SDK_PATH AND NOT PICO_SDK_PATH STREQUAL "")
    file(GLOB ELEC_C7222_BLE_GATT_SOURCES "${ELEC_C7222_BLE_GATT_DIR}/platform/rpi_pico/*.cpp")
else()
    file(GLOB ELEC_C7222_BLE_GATT_SOURCES "${ELEC_C7222_BLE_GATT_DIR}/platform/grader/*.cpp")
endif()
file(GLOB ELEC_C7222_BLE_GATT_SOURCES_COMMON "${ELEC_C7222_BLE_GATT_DIR}/src/*.cpp")

add_library(ELEC_C7222_BLE_GATT INTERFACE)
target_sources(ELEC_C7222_BLE_GATT INTERFACE 
                    ${ELEC_C7222_BLE_GATT_SOURCES} 
                    ${ELEC_C7222_BLE_GATT_SOURCES_COMMON})

target_include_directories(ELEC_C7222_BLE_GATT INTERFACE "${ELEC_C7222_BLE_GATT_DIR}/include")
