set(ELEC_C7222_BLE_SECURITY_MANAGER_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_BLE_SECURITY_MANAGER_SOURCES
    "${ELEC_C7222_BLE_SECURITY_MANAGER_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.cpp")
file(GLOB ELEC_C7222_BLE_SECURITY_MANAGER_SOURCES_COMMON "${ELEC_C7222_BLE_SECURITY_MANAGER_DIR}/src/*.cpp")

add_library(ELEC_C7222_BLE_SECURITY_MANAGER INTERFACE)
target_sources(ELEC_C7222_BLE_SECURITY_MANAGER INTERFACE 
                    ${ELEC_C7222_BLE_SECURITY_MANAGER_SOURCES} 
                    ${ELEC_C7222_BLE_SECURITY_MANAGER_SOURCES_COMMON})

target_include_directories(ELEC_C7222_BLE_SECURITY_MANAGER INTERFACE "${ELEC_C7222_BLE_SECURITY_MANAGER_DIR}/include")
