set(ELEC_C7222_PLATFORM_DIR ${CMAKE_CURRENT_LIST_DIR})

if (DEFINED PICO_SDK_PATH AND NOT PICO_SDK_PATH STREQUAL "")
    file(GLOB ELEC_C7222_PLATFORM_SOURCES "${ELEC_C7222_PLATFORM_DIR}/rpi_pico/*.cpp")
else()
    file(GLOB ELEC_C7222_PLATFORM_SOURCES "${ELEC_C7222_PLATFORM_DIR}/grader/*.cpp")
endif()

add_library(ELEC_C7222_PLATFORM INTERFACE)
target_sources(ELEC_C7222_PLATFORM INTERFACE ${ELEC_C7222_PLATFORM_SOURCES})
target_include_directories(ELEC_C7222_PLATFORM INTERFACE "${ELEC_C7222_PLATFORM_DIR}/include")