if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

if(NOT C7222_ENABLE_BLE)
    message(STATUS "C7222_EXAMPLES_BUILD requires C7222_ENABLE_BLE=ON for BLE examples. Skipping BLE GATT SERVER example...")
    return()
endif()

add_library(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE)
set_property(TARGET C7222_EXAMPLE_BLE_GATT_SERVER PROPERTY TARGET_NAME "example-ble-gatt-server")
set_property(TARGET C7222_EXAMPLE_BLE_GATT_SERVER PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_BLE_GATT_SERVER_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.cpp
)

target_sources(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE
    ${C7222_EXAMPLE_BLE_GATT_SERVER_SOURCES}
)

target_include_directories(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/../common
)

# Append the gatt files 
file(GLOB APP_GATT_FILES "${CMAKE_CURRENT_LIST_DIR}/*.gatt")
set_property(TARGET C7222_EXAMPLE_BLE_GATT_SERVER APPEND PROPERTY GATT_FILES ${APP_GATT_FILES})
# append to the global list for examples to use
list(APPEND C7222_EXAMPLES C7222_EXAMPLE_BLE_GATT_SERVER)
