if(NOT DEFINED C7222_EXAMPLE_BLE_GATT_SERVER)
    set(C7222_EXAMPLE_BLE_GATT_SERVER OFF)
endif()
if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

message(STATUS "C7222_EXAMPLE_BLE_GATT_SERVER is defined: ${C7222_EXAMPLE_BLE_GATT_SERVER}")

if(C7222_EXAMPLE_BLE_GATT_SERVER)
    if(NOT C7222_ENABLE_BLE)
        message(FATAL_ERROR "C7222_EXAMPLE_BLE_GATT_SERVER requires C7222_ENABLE_BLE=ON")
    endif()
    add_library(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE)

    file(GLOB C7222_EXAMPLE_BLE_GATT_SERVER_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/*.c
        ${CMAKE_CURRENT_LIST_DIR}/../common/*.c
        ${CMAKE_CURRENT_LIST_DIR}/*.cpp
        ${CMAKE_CURRENT_LIST_DIR}/../common/*.cpp
    )

    target_sources(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE
        ${C7222_EXAMPLE_BLE_GATT_SERVER_SOURCES}
    )

    target_include_directories(C7222_EXAMPLE_BLE_GATT_SERVER INTERFACE
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/../common
    )

    list(APPEND C7222_ENABLED_EXAMPLES C7222_EXAMPLE_BLE_GATT_SERVER)
endif()
