add_library(C7222_EXAMPLE_FREERTOS_DEVICE_CPP INTERFACE)
set_property(TARGET C7222_EXAMPLE_FREERTOS_DEVICE_CPP PROPERTY TARGET_NAME "example-freertos-device-cpp")
set_property(TARGET C7222_EXAMPLE_FREERTOS_DEVICE_CPP PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_FREERTOS_DEVICE_CPP_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/*.hpp
    ${CMAKE_CURRENT_LIST_DIR}/*.h
)

target_sources(C7222_EXAMPLE_FREERTOS_DEVICE_CPP INTERFACE
    ${C7222_EXAMPLE_FREERTOS_DEVICE_CPP_SOURCES}
)

target_include_directories(C7222_EXAMPLE_FREERTOS_DEVICE_CPP INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
)

list(APPEND C7222_EXAMPLES C7222_EXAMPLE_FREERTOS_DEVICE_CPP)
