if(NOT DEFINED C7222_ENABLE_BLE)
    set(C7222_ENABLE_BLE OFF)
endif()

if(NOT C7222_ENABLE_BLE)
    message(STATUS "Skipping BLE custom-service-rw example (C7222_ENABLE_BLE=OFF)")
    return()
endif()

add_library(C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW INTERFACE)
set_property(TARGET C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW PROPERTY TARGET_NAME "example-ble-custom-service-rw")
set_property(TARGET C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW PROPERTY TARGET_PATH "${CMAKE_CURRENT_LIST_DIR}")

file(GLOB C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/*.c
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.c
    ${CMAKE_CURRENT_LIST_DIR}/*.cpp
    ${CMAKE_CURRENT_LIST_DIR}/../common/*.cpp
)

target_sources(C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW INTERFACE
    ${C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW_SOURCES}
)

target_include_directories(C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/../common
)

# Register .gatt files for header generation
file(GLOB APP_GATT_FILES "${CMAKE_CURRENT_LIST_DIR}/*.gatt")
set_property(TARGET C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW APPEND PROPERTY GATT_FILES ${APP_GATT_FILES})

# Register example in the global list
list(APPEND C7222_EXAMPLES C7222_EXAMPLE_BLE_CUSTOM_SERVICE_RW)
