set(ELEC_C7222_UTILS_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_UTILS_SOURCES "${ELEC_C7222_UTILS_DIR}/src/*.cpp")

add_library(ELEC_C7222_UTILS INTERFACE)
target_sources(ELEC_C7222_UTILS INTERFACE ${ELEC_C7222_UTILS_SOURCES})
target_include_directories(ELEC_C7222_UTILS INTERFACE "${ELEC_C7222_UTILS_DIR}/include")
