set(ELEC_C7222_UTILS_DIR ${CMAKE_CURRENT_LIST_DIR})

file(GLOB ELEC_C7222_UTILS_PLATFORM_SOURCES
    "${ELEC_C7222_UTILS_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.cpp"
    "${ELEC_C7222_UTILS_DIR}/platform/${C7222_PLATFORM_SOURCE_DIR}/*.c")

file(GLOB ELEC_C7222_UTILS_SOURCES
    "${ELEC_C7222_UTILS_DIR}/src/*.cpp"
    "${ELEC_C7222_UTILS_DIR}/src/*.c")

add_library(ELEC_C7222_UTILS INTERFACE)

target_sources(ELEC_C7222_UTILS
    INTERFACE
    ${ELEC_C7222_UTILS_SOURCES}
    ${ELEC_C7222_UTILS_PLATFORM_SOURCES})

target_include_directories(ELEC_C7222_UTILS
    INTERFACE
    "${ELEC_C7222_UTILS_DIR}/include")
